---
# Remove things created by common initialization play (webproxy, certificates, repositories)
- hosts: all
  user: deployer
  become: yes
  tasks:
    - name: Remove kubernetes repository
      apt_repository:
        filename: Kubernetes
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: absent

    - name: Remove docker repository
      apt_repository:
        filename: Docker
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu/ xenial stable amd64
        state: absent

    - name: Stop services
      systemd:
        name={{ item }}
        state=stopped
        enabled=no
      with_items:
        - kubelet
        - docker
      ignore_errors: yes

    - name: Remove required packages
      apt: name={{ item }} state=absent
      with_items:
        - "docker-ce"

    - name: Remove files
      file: path={{ item }} state=absent
      with_items:
        - /etc/systemd/system/docker.service.d
        - /etc/systemd/system/kubelet.service
        - /etc/kubernetes
        - /etc/docker

    - name: Unmount docker resources
      shell: umount /run/docker/netns/*
      ignore_errors: yes

- hosts: masters
  user: deployer
  become: yes
  tasks:
    - name: Remove files
      file: path={{ item }} state=absent
      with_items:
        - /root/.helm/repository/repositories.yaml
        - /usr/bin/helm-{{helm_version}}
        - /usr/bin/helm
        - /usr/bin/etcd-{{etcd_version}}
        - /usr/bin/etcd
        - /usr/bin/etcdctl-{{etcd_version}}
        - /usr/bin/etcdctl
        - /var/lib/etcd
        - /etc/systemd/system/etcd.service
        - /etc/sensu/conf.d/nais_master_metrics.json
    - name: Disable etcd
      systemd: name=etcd enabled=no state=stopped
      ignore_errors: yes

- hosts: workers
  user: deployer
  become: yes
  tasks:
    - name: Remove files
      file: path={{ item }} state=absent
      with_items:
        - /etc/sensu/conf.d/nais_worker_metrics.json

- hosts: localhost
  tasks:
    - name: Remove target folder
      file: path=target state=absent

- hosts: all
  user: deployer
  become: yes
  tasks:
  - name: Stop services
    systemd:
      name={{ item }}
      state=stopped
      enabled=no
    with_items:
      - kube-proxy
      - flannel
    ignore_errors: yes

  - name: Remove files
    file: path={{ item }} state=absent
    with_items:
      - /etc/systemd/system/kubelet.service
      - /usr/bin/kube-proxy*
      - /usr/bin/kubelet*
      - /usr/bin/kubectl*
      - /etc/systemd/system/kube-proxy.service
      - /usr/libexec/mk-docker-opts.sh
      - /usr/bin/flanneld
      - /etc/systemd/system/flannel.service
      - /etc/systemd/system/docker.service
      - /usr/bin/flanneld-{{flannel_version}}
      - /run/docker_opts.env
      - /run/flannel/subnet.env
      - /var/run/docker
      - /var/run/flannel
      - /var/run/kubernetes
      - /run/docker
      - /run/flannel
      - /run/kubernetes

  - name: Remove docker interface
    shell: ip link delete docker0
    ignore_errors: yes

  - name: Remove flannel interface
    shell: ip link delete flannel.1
    ignore_errors: yes

  - name: Remove nais sensu check directory
    file: path=/etc/sensu/plugins/metrics/nais state=absent
