- name: Check master for CA cert
  stat:
    path: /etc/kubernetes/pki/ca.pem
  register: ca

- name: Check master for api-server-server cert
  stat:
    path: /etc/kubernetes/pki/kube-apiserver-server.pem
  register: apiserver

- name: Check master for service account key
  stat:
    path: /etc/kubernetes/pki/sa.key
  register: sa

- name: Check master for admin cert
  stat:
    path: /etc/kubernetes/pki/admin.pem
  register: admin

- fetch:
    src: /etc/kubernetes/pki/ca.pem
    dest: target/pki/
    flat: yes
  when: ca.stat.exists

- fetch:
    src: /etc/kubernetes/pki/ca-key.pem
    dest: target/pki/
    flat: yes
  when: ca.stat.exists

- fetch:
    src: /etc/kubernetes/pki/admin.pem
    dest: target/pki/
    flat: yes
  when: admin.stat.exists

- fetch:
    src: /etc/kubernetes/pki/admin-key.pem
    dest: target/pki/
    flat: yes
  when: admin.stat.exists

- fetch:
    src: /etc/kubernetes/pki/kube-apiserver-server.pem
    dest: target/pki/
    flat: yes
  when: apiserver.stat.exists

- fetch:
    src: /etc/kubernetes/pki/kube-apiserver-server-key.pem
    dest: target/pki/
    flat: yes
  when: apiserver.stat.exists

- fetch:
    src: /etc/kubernetes/pki/sa.key
    dest: target/pki/
    flat: yes
  when: sa.stat.exists

- fetch:
    src: /etc/kubernetes/pki/sa.pub
    dest: target/pki/
    flat: yes
  when: sa.stat.exists
